### ISSUE TITLE
Consider making `--strip-hidden-doc` the default

### ISSUE THREAD

**Issue by orium** [phaazon/cargo-sync-readme#10]
I think most users will want the README to look like the rust documentation.  I think it would be nice to make `--strip-hidden-doc` the default and add flags to opt out.

**Comment by phaazon** [comment]
So you would reverse this behavior? Interesting. :)

**Comment by orium** [comment]
Yes, I would remove `--strip-hidden-doc` and add `--no-strip-hidden-doc` or something similar.  I think most users would want the "strip hidden doc" by default.

**Comment by phaazon** [comment]
You might be right. Thank you for your hindsight, I’ll change that!

**Comment by phaazon** [comment]
Done in [cargo-sync-readme-0.2](https://crates.io/crates/cargo-sync-readme).
