### ISSUE TITLE
Rustdoc intra-links should be translated to links to doc.rs 

### ISSUE THREAD

**Issue by orium** [phaazon/cargo-sync-readme#11]
An intra-link inside rustdoc will not work in the README.

Example:

If we have this in `lib.rs`:

```rust
//! +Archery defines a [`SharedPointer`](./shared_pointer/struct.SharedPointer.html)
```

the README should probably become:

```text
Archery defines a [`SharedPointer`](https://docs.rs/archery/latest/archery/shared_pointer/struct.SharedPointer.html)
```

**Comment by orium** [comment]
If this gets implemented I can finally throw away [this ugly script](https://github.com/orium/archery/blob/master/tools/update-readme.sh) :slightly_smiling_face:

**Comment by phaazon** [comment]
Yeah, this is a really good point. Not trivial to do though, because it’s possible to have several syntaxes.

**Comment by phaazon** [comment]
I will start by recognizing the absolute syntax:

    crate::something::foo:bar::quux

However, I guess I need to use `syn` to detect the type of a given item and create the URL…

**Comment by zbraniecki** [comment]
It would be great to have an ability to customize the docs path (instead of hardcoding `docs.rs`) - we use live docs in a custom github pages location and would prefer to link our readme to that.

**Comment by zbraniecki** [comment]
Now that the intra-doc links are in Rust stable, I'm interested in trying to tackle this issue.

My architectural approach is to add a function `expand_intra_doc_links(line: &str, docs_url: &str) -> String` which will take a line like `Hello to [Struct](super::Struct)` or `[Struct]: super::Struct` or `[Struct]` and convert it to `[Struct](https://docs.rs/my_crate/struct.Struct.html)`.

The first challenge is that I'm not sure how to extract relative paths for docs based on `super::Struct` or just `Struct`.

I assume there must be a `rustdoc` command that allows me to call something like `rustdoc get_path --manifest Cargo.toml super::Struct` that returns `component/struct.Struct.html` which I can merge with the path to `docs.rs` to construct a path, but I have not found one yet.

Anyone knows how to get it?

**Comment by orium** [comment]
@zbraniecki I have a PR that is almost ready for this :)

**Comment by orium** [comment]
PR #35 is ready for review :slightly_smiling_face:.  It should close this ticket entirely because it still needs support for at least `std`/`code`/`alloc`.

**Comment by phaazon** [comment]
I’ll have a look by the end of the day.

**Comment by orium** [comment]
@phaazon Feel free to ping me if there are any bug reports related to this feature after the release.  I should be able to look intro those soon after that.

**Comment by phaazon** [comment]
I’ll make some changes about it because it doesn’t support footer links, like:

```
Foo [bar] zoo

[bar]: https://bar.xyz
```
