### ISSUE TITLE
Problem with inner comments and tabulations

### ISSUE THREAD

**Issue by jesusprubio** [phaazon/cargo-sync-readme#14]
I have problems with the default rustfmt setup, because it tabs the inner doc. Am I losing something?

This works:

```rust
/// myfun description
pub fn myfun() -> bool {
//! ```rust
//! extern crate myfun;
//! use myfun::*;
//!
//! assert_eq!(myfun(), true);
//! ```
...
```

This doesn't work:
```rust
/// myfun description
pub fn myfun() -> bool {
    //! ```rust
    //! extern crate myfun;
    //! use myfun::*;
    //!
    //! assert_eq!(myfun(), true);
    //! ```
...
```

Thank you!

**Comment by phaazon** [comment]
Wait, I don’t get your issue. `cargo-sync-readme` only works on the crate-level documentation, not on items.

**Comment by jesusprubio** [comment]
Sorry, I mean I'm using it for the whole crate. But if I indent the inner comments an empty line is added to the README file.

Maybe I'm misundertanding the goal but it works for me if I don't indent the inner documentation.

**Comment by phaazon** [comment]
Oh, ok, I see the problem now. Thanks for reporting! I’ll fix it ASAP! :)

**Comment by phaazon** [comment]
It wasn’t as ASAP as I would have liked it to be, but the fix has landed and was released on crates.io. Thanks again for reporting @jesusprubio. Closing.
