### ISSUE TITLE
should_panic doctests get the wrong language

### ISSUE THREAD

**Issue by leo60228** [phaazon/cargo-sync-readme#47]
This input:
```rust
/// ```should_panic
/// fn main() {}
/// ```
```
leads to this `README.md`:
```markdown
﻿```should_panic
fn main() {}
﻿```
```

**Comment by phaazon** [comment]
Hello.

Thanks for reporting! I’ll have a look at this tomorrow. :)

**Comment by phaazon** [comment]
This is fixed and will be released soon with the rest of the recent changes. I have a long session of refactoring, cleaning and optimization to do so expect a bit of time until the next release, but it should arrive soon.
