### ISSUE TITLE
Allow hiding a portion of an example

### ISSUE THREAD

**Issue by lovasoa** [phaazon/cargo-sync-readme#5]
Cargo doctests have a feature where parts of a documentation test can be hidden:

```
/// # fn foo() {} // this function will be hidden
```

see: https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example

It would be nice if this feature were supported.

**Comment by phaazon** [comment]
Yeah, that’s a nice feature to have! I’ll work on it! Thanks for reporting!

**Comment by phaazon** [comment]
Released as part of [cargo-sync-readme-0.1.3](https://crates.io/crates/cargo-sync-readme/0.1.3).
