### ISSUE TITLE
intra-links to docs.rs fail if hyphen in package name

### ISSUE THREAD

**Issue by ahirner** [phaazon/cargo-sync-readme#57]
In [backtrack-rs](https://github.com/ahirner/backtrack-rs) I have intra-links pointing e.g. to:
https://docs.rs/backtrack-rs/latest/backtrack-rs/problem/trait.Scope.html
.. while they should point to:
https://docs.rs/backtrack-rs/latest/backtrack_rs/problem/trait.Scope.html

After [this](https://github.com/rust-lang/rfcs/blob/master/text/0940-hyphens-considered-harmful.md), cargo and docs.rs distinguish between package name and crate name. I think a simple solution is replacing `-` by `_` for the 2nd argument to `format!` [here](https://github.com/phaazon/cargo-sync-readme/blob/master/src/intralinks.rs#L498).

**Comment by orium** [comment]
Thanks for reporting.  Fix in PR #58.

**Comment by ahirner** [comment]
Thanks a bunch for the quick reply! Any plans for a new release? I'm asking because `cargo-sync-readme` is part of my CI rn ;)
