### ISSUE TITLE
cargo-sync-readm doesn't work on Windows

### ISSUE THREAD

**Issue by Riduidel** [phaazon/cargo-sync-readme#7]
Since detection is done on `<!-- cargo-sync-readme -->\n` This doesn't work (with a poor error message) when `README.md` is Windows encoded (ie using `\r\n`)

**Comment by phaazon** [comment]
Thanks for opening this. I will fix that ASAP.

**Comment by phaazon** [comment]
That should be fixed, but I need to find a way to test.

**Comment by Riduidel** [comment]
Maybe you could ... test it through travis CI or another CI platform ...

I know it's not a perfect solution, but it will help ... I guess

Le 10/05/2019 à 15:45, Dimitri Sabadie a écrit :

**Comment by phaazon** [comment]
Yeah, I need to write a small README example that tests it. The fix is already written, I’ll try to push to crates.io ASAP. :)

**Comment by phaazon** [comment]
@Riduidel can you try the latest [0.1.5](https://crates.io/crates/cargo-sync-readme/0.1.5) and tell me if the `--crlf` option works correctly for you? :)
