### ISSUE TITLE
Escaping brakes in code fragments?

### ISSUE THREAD

**Issue by blyxyas** [phaazon/cargo-sync-readme#88]
I have an index  in my last project, the troubling section looks something like this:

```
* [`cuteconfig.toml`](#cuteconfig)
    * [`[routing]`](#config.routing)
    * [`[misc]`](#config.misc)
    * [`[config]`](#config.config)
```

This should render to:

* [`cuteconfig.toml`](#cuteconfig)
    * [`[routing]`](#config.routing)
    * [`[misc]`](#config.misc)
    * [`[config]`](#config.config)

---

Instead, after synchronizing it renders this:

```
* [`cuteconfig.toml`](#cuteconfig)
    * [`\[routing\]`](#config.routing)
    * [`\[misc\]`](#config.misc)
    * [`\[config\]`](#config.config)
```

Which renders to:

* [`cuteconfig.toml`](#cuteconfig)
    * [`\[routing\]`](#config.routing)
    * [`\[misc\]`](#config.misc)
    * [`\[config\]`](#config.config)

So the problem is that the program escape square brackets in code fragments when it's not necessary.

**Comment by orium** [comment]
Try [cargo-rdme](https://github.com/orium/cargo-rdme): it doesn't have that issue.

(I'm the author of that crate btw.)
